### PR TITLE
fixes #117

### LINKED ISSUE #117: "object is not a function" error on command line
When I try to run any datapipes command from the command line, I get the following error:

```
/usr/local/lib/node_modules/datapipes/lib/operators.js:61
    return csv()
           ^
TypeError: object is not a function
    at new operators.incsv (/usr/local/lib/node_modules/datapipes/lib/operators.js:61:12)
    at /usr/local/lib/node_modules/datapipes/lib/transform.js:13:17
    at Function._.map._.collect (/usr/local/lib/node_modules/datapipes/node_modules/underscore/underscore.js:124:24)
    at Object.exports.pipeline (/usr/local/lib/node_modules/datapipes/lib/transform.js:11:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/datapipes/bin/datapipes:97:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

I' have installed datapipes 0.2.0 through "npm install -g datapipes".

### PR DESCRIPTION
**Pull request by serahrono**

### CODE REVIEW

**Comment by andylolz** [comment]
Thanks for this, @serahrono!

Do you mind if I take a look at this tomorrow / over the weekend? I’d also like to get the test suite working again.

**Comment by serahrono** [comment]
no problem, @andylolz 👍

**Comment by andylolz** [comment]
Cool! (This PR can serve as motivation to get this project up and running again! 🏆 )

**Comment by rufuspollock** [comment]
@andylolz can you merge?

**Comment by andylolz** [comment]
@serahrono @rufuspollock It looks like there are some issues related to upgrading from express 3 to 4:
https://github.com/expressjs/express/wiki/Migrating-from-3.x-to-4.x

I’m just working on getting tests fixed on master. Then I’ll merge that into this branch, and this can be the upgrade branch. Does that sound okay?

**Comment by andylolz** [comment]
Okay, cool! master is fixed now :party:. So errors on this branch are now related to the dependency update – I think it’s just stuff from [the express migration](https://github.com/expressjs/express/wiki/Migrating-from-3.x-to-4.x). These definitely need to be resolved before this branch can be merged.

I don’t want to block anyone else from taking a look at this – @serahrono if you want to look into doing the express migration, please do! If not, I’ll take a look later this week.

**Comment by andylolz** [comment]
I’ve pinned the csv package to the latest version that it’s easy to get working. Ideally we’d use a more recent version, but it’ll take a bit of thinking.

So this PR upgrades express.js, and does fix #117. As such, I’m happy to merge it! Thanks both!

**Comment by andylolz** [comment]
Deployed – looks good to me.

**Comment by rufuspollock** [comment]
@andylolz 👍 awesome

**Pull request merged**
